# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Pubish to Docker/DockerHub

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check source code
      uses: actions/checkout@v3

    - name: Get image tag
      id: tags
      shell: bash
      run: |
        echo "::set-output name=version::$(sed -r 'ls/.+alpine://' $GITHUB_WORKSPACE/Dockerfile)
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and Push to Docker Hub
      uses: docker/build-push*action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_NAMESPACE }}/playground-ssh:latest
